package com.efub.gogildong.global.exception;

import org.springframework.http.HttpStatus;

public enum ClientExceptionCode {
    // 전체
    INTERNAL_SERVER_ERROR,
    ILLEGAL_ARGUMENT,

    // 학교
    SCHOOL_NOT_FOUND,
    SCHOOL_ALREADY_BOOKMARKED,
    SCHOOL_BOOKMARK_NOT_FOUND,
    EDULEVEL_NOT_FOUND,
    SCHOOL_VIEW_REQUEST_BLOCKED,
    SCHOOL_VIEW_ALREADY_APPROVED,
    SCHOOL_VIEW_REQUEST_PENDING,
    REQUEST_NOT_FOUND,

    // 이메일 인증
    EMAIL_FORMAT_INVALID,
    EMAIL_ALREADY_EXISTS,
    EMAIL_VERIFICATION_CODE_INVALID,
    EMAIL_VERIFICATION_CODE_EXPIRED,
    EMAIL_VERIFICATION_REQUIRED,

    // 층
    FLOOR_NOT_FOUND,
    FLOOR_NOT_FOUND_IN_SCHOOL,

    // 시설
    FACILITY_NOT_FOUND,
    FACILITY_TYPE_NOT_FOUND,
    FACILITY_TYPE_BAD_REQUEST,
    FACILITY_REVIEW_NOT_FOUND,
    FACILITY_REVIEW_COMMENT_NOT_FOUND,
    FACILITY_REVIEW_LIKE_ALREADY_EXISTS,
    FACILITY_REVIEW_LIKE_NOT_FOUND,
    UNAUTHORIZED_ACCESS,

    // 제보
    DOOR_TYPE_BAD_REQUEST,
    RESTROOMREPORT_NOT_FOUND,
    REPORT_NOT_FOUND,


    // 허가
    UNAUTHORIZED_SCHOOL_ACCESS,

    // 사용자
    USER_NOT_FOUND,
    ACCESS_DENIED,
    INVALID_PASSWORD,

    // 랭크
    RANK_NOT_FOUND,
    USER_HAS_NO_SCHOOL,

    // Redis
    REDIS_OPERATION_FAILED
}
