package com.efub.gogildong.global.exception;

public enum ClientExceptionCode {
    // 전체
    INTERNAL_SERVER_ERROR,
    ILLEGAL_ARGUMENT,

    // 학교
    SCHOOL_NOT_FOUND,
    SCHOOL_ALREADY_BOOKMARKED,
    SCHOOL_BOOKMARK_NOT_FOUND,
    EDULEVEL_NOT_FOUND,
    SCHOOL_VIEW_ALREADY_APPROVED,
    SCHOOL_VIEW_REQUEST_PENDING,

    // 층
    FLOOR_NOT_FOUND,
    FLOOR_NOT_FOUND_IN_SCHOOL,

    // 시설
    FACILITY_NOT_FOUND,
    FACILITY_TYPE_NOT_FOUND,
    FACILITY_TYPE_BAD_REQUEST,
    FACILITY_REVIEW_NOT_FOUND,
    FACILITY_REVIEW_COMMENT_NOT_FOUND,
    FACILITY_REVIEW_LIKE_ALREADY_EXISTS,
    FACILITY_REVIEW_LIKE_NOT_FOUND,
    UNAUTHORIZED_ACCESS,

    // 제보
    DOOR_TYPE_BAD_REQUEST,
    REPORT_NOT_FOUND,

    // 허가
    UNAUTHORIZED_SCHOOL_ACCESS,

    // 사용자
    USER_NOT_FOUND,
    ACCESS_DENIED,
    INVALID_PASSWORD
}
